export const LOGIN_INPUT_CHANGED = 'LOGIN_INPUT_CHANGED';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const USER_LOGOUT = 'USER_LOGOUT';

export const EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE';
export const EMPLOYEE_CREATE = 'EMPLOYEE_CREATE';

export const EMPLOYEES_FETCH_SUCCESS = 'EMPLOYEE_FETCH_SUCCESS';
export const EMPLOYEES_FETCH_PENDING = 'EMPLOYEE_FETCH_PENDING';

